substrate-developer-hub/substrate-parachain-template

Cargo.lock
README.md
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/parachain-info/Cargo.toml
pallets/token-dealer/Cargo.toml
runtime/Cargo.toml

Updates and pins to Cumulus commit `96da14c`

Update to Cumulus 96da14c

---

Cargo.lock
README.md
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs
node/src/service.rs
pallets/parachain-info/Cargo.toml
pallets/parachain-info/src/lib.rs
pallets/token-dealer/Cargo.toml
pallets/token-dealer/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Shouldn't be merged until we have the workshop companion PR
Also fixes #3

Update to Cumulus 35f60b1

---

Cargo.lock
node/Cargo.toml
pallets/parachain-info/Cargo.toml
pallets/token-dealer/Cargo.toml
runtime/Cargo.toml

Update Cumulus, Substrate and Polkadot.

Update to Cumulus 4e7f138

---

node/src/service.rs

use the template and find out the ocw not triggered. the pr enable ocw in node.

enable ocw

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/service.rs
runtime/src/lib.rs

Update template to match cumulus 
Ref : [#325](https://github.com/paritytech/cumulus/pull/325) and [#342](https://github.com/paritytech/cumulus/pull/342)

fix:match cumulus refactoring

---

node/src/service.rs

#13  is somehow deleted in #14

bring back ocw

---

Cargo.lock
node/Cargo.toml
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

Tested by changing spec to rococo-local. FYI I saw Basti mention in the room that wentend was left unintentionally so might be best to change it back to avoid waiting an hour for epoc registration

update to 0.9.3

---

node/src/command.rs

rollback expect para_id

---

.rustfmt.toml
node/src/chain_spec.rs
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/template/src/lib.rs
pallets/template/src/mock.rs
pallets/template/src/tests.rs
runtime/src/lib.rs
rustfmt.toml

Add rustfmt, run `cargo +nightly fmt`

---

.github/workflows/test-code.yml
Cargo.lock
README.md
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Update to `polkadot-v0.9.10`

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Compiled successfully using
```
1.58-x86_64-unknown-linux-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

Update to polkadot-v0.9.15

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

patch release, cumulus was not patched.

update to polkadot v0.9.15-1

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/xcm_config.rs

- xcm configuramtion updates
- tweaks on commands for benchmarks, try-runtime

Update to upstream polkadot-v0.9.19

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/rpc.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

Part of https://github.com/substrate-developer-hub/substrate-docs/pull/1045.

Update to polkadot-v0.9.22

---

Cargo.lock

update to include backport in lockfile

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/rpc.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

Update to https://github.com/paritytech/polkadot/releases/tag/v0.9.23
- Tested!

update to polkadot-v0.9.23

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

Update to https://github.com/paritytech/polkadot/releases/tag/v0.9.24
- Tested!

Update to polkadot-v0.9.24

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
pallets/template/Cargo.toml
polkadot-launch/config.json
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/xcm_config.rs

Polkadot v0.9.25 Release
- https://github.com/paritytech/polkadot/releases/tag/v0.9.25
Tested!

Update to polkadot-v0.9.25

---

.github/workflows/test-code.yml
Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/rpc.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Polkadot v0.9.26 Release:
- https://github.com/paritytech/polkadot/releases/tag/v0.9.26
Tested!

Update to polkadot-v0.9.26

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

Auto-Update node-template from polkadot-v0.9.27

Auto-Update node-template from polkadot-v0.9.27

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

Auto-Update substrate-parachain-template from polkadot-v0.9.28

Auto-Update substrate-parachain-template from polkadot-v0.9.28

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/weights/paritydb_weights.rs
runtime/src/weights/rocksdb_weights.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.29

Auto-Update substrate-parachain-template from polkadot-v0.9.29

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
pallets/template/src/mock.rs
pallets/template/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/weights/paritydb_weights.rs
runtime/src/weights/rocksdb_weights.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.30

Auto-Update substrate-parachain-template from polkadot-v0.9.30

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.32

Auto-Update substrate-parachain-template from polkadot-v0.9.32

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/weights/paritydb_weights.rs
runtime/src/weights/rocksdb_weights.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.36

Auto-Update substrate-parachain-template from polkadot-v0.9.36

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.37

Auto-Update substrate-parachain-template from polkadot-v0.9.37

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.40

Auto-Update substrate-parachain-template from polkadot-v0.9.40

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/build.rs
runtime/src/lib.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.42

Auto-Update substrate-parachain-template from polkadot-v0.9.42

---

Cargo.lock
README.md
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/benchmarking.rs
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/xcm_config.rs

Auto-Update substrate-parachain-template from polkadot-v0.9.43

Auto-Update substrate-parachain-template from polkadot-v0.9.43

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

Updates to remove the need to the intermediate #194 PR to the _real deal_ :grin:

Update to formal polkadot-v1.0.0 release for deps
